accounts:
- '987654321012'
archive_name: term-cloud-iac/dev/dryrun/config.zip
asset_insight_id: '204503'
deployment_engine_version: 1.3.0
environment_order:
- dev
- prod
financial_identifier: '66497'
github_branch: master
github_owner: jack-farrell28
github_repo: term-cloud-iac
log_retention: 90
project_code: a204503-service-term-cloud-iac
project_name: term-cloud-iac
region: us-east-1
resource_owner: Jack.Farrell@thomsonreuters.com
service_name: service
source_bucket: a204503-github-iac-j-farrell-us-east-1-cfn
spring_config_urls:
  mySpringConfig1: http://ex.config1.url
  mySpringconfig2: http://ex.config2.url
template_bucket_name: a204503-github-iac-j-farrell-us-east-1-cfn
template_key_prefix: iac-test-prefix
